ALTER TABLE team_member_schedule
    ADD COLUMN IF NOT EXISTS coverage_days VARCHAR(128) NOT NULL DEFAULT 'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY';

UPDATE team_member_schedule
SET coverage_days = 'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY'
WHERE coverage_days IS NULL OR trim(coverage_days) = '';
