create table organization (
    org_id bigint generated by default as identity primary key,
    name varchar(255) not null,
    slug varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    constraint uq_organization_name unique (name),
    constraint uq_organization_slug unique (slug)
);

create table team (
    team_id bigint generated by default as identity primary key,
    org_id bigint not null,
    name varchar(255) not null,
    description varchar(255),
    join_code varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    constraint uq_team_join_code unique (join_code),
    constraint fk_team_org foreign key (org_id) references organization (org_id)
);

create table users (
    u_id bigint generated by default as identity primary key,
    username varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    created_by bigint,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    current_org_id bigint,
    current_team_id bigint,
    constraint uq_users_username unique (username),
    constraint fk_users_current_org foreign key (current_org_id) references organization (org_id),
    constraint fk_users_current_team foreign key (current_team_id) references team (team_id)
);

create table organization_membership (
    membership_id bigint generated by default as identity primary key,
    u_id bigint not null,
    org_id bigint not null,
    role varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    constraint uq_org_membership unique (u_id, org_id),
    constraint fk_org_membership_user foreign key (u_id) references users (u_id),
    constraint fk_org_membership_org foreign key (org_id) references organization (org_id)
);

create table geo (
    g_id bigint generated by default as identity primary key,
    name varchar(255) not null,
    team_id bigint,
    constraint uq_geo_team_name unique (team_id, name),
    constraint fk_geo_team foreign key (team_id) references team (team_id)
);

create table shift (
    s_id bigint generated by default as identity primary key,
    name varchar(255) not null,
    team_id bigint,
    constraint uq_shift_team_name unique (team_id, name),
    constraint fk_shift_team foreign key (team_id) references team (team_id)
);

create table configuration_item (
    ci_id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(255),
    service_now_sys_id varchar(255),
    team_id bigint,
    constraint uq_ci_team_name unique (team_id, name),
    constraint uq_ci_team_sys_id unique (team_id, service_now_sys_id),
    constraint fk_ci_team foreign key (team_id) references team (team_id)
);

create table team_member (
    tm_id bigint generated by default as identity primary key,
    f_name varchar(255) not null,
    l_name varchar(255) not null,
    email varchar(255) not null,
    phone varchar(255),
    sys_id varchar(255),
    g_id bigint,
    team_id bigint,
    constraint uq_team_member_email unique (team_id, email),
    constraint uq_team_member_sys_id unique (team_id, sys_id),
    constraint fk_team_member_geo foreign key (g_id) references geo (g_id),
    constraint fk_team_member_team foreign key (team_id) references team (team_id)
);

create table geo_shift_mapping (
    gsm_id bigint generated by default as identity primary key,
    g_id bigint not null,
    s_id bigint not null,
    team_id bigint,
    constraint uq_geo_shift_mapping unique (team_id, g_id, s_id),
    constraint fk_geo_shift_mapping_geo foreign key (g_id) references geo (g_id),
    constraint fk_geo_shift_mapping_shift foreign key (s_id) references shift (s_id),
    constraint fk_geo_shift_mapping_team foreign key (team_id) references team (team_id)
);

create table ci_user_mapping (
    mapping_id bigint generated by default as identity primary key,
    ci_id bigint not null,
    tm_id bigint not null,
    sort_order integer,
    team_id bigint,
    constraint uq_ci_user_mapping unique (team_id, ci_id, tm_id),
    constraint fk_ci_user_mapping_ci foreign key (ci_id) references configuration_item (ci_id),
    constraint fk_ci_user_mapping_member foreign key (tm_id) references team_member (tm_id),
    constraint fk_ci_user_mapping_team foreign key (team_id) references team (team_id)
);

create table team_member_schedule (
    tms_id bigint generated by default as identity primary key,
    tm_id bigint not null,
    g_id bigint not null,
    s_id bigint not null,
    team_id bigint,
    start_date date not null,
    end_date date not null,
    constraint fk_schedule_member foreign key (tm_id) references team_member (tm_id),
    constraint fk_schedule_geo foreign key (g_id) references geo (g_id),
    constraint fk_schedule_shift foreign key (s_id) references shift (s_id),
    constraint fk_schedule_team foreign key (team_id) references team (team_id)
);

create table leave (
    leave_id bigint generated by default as identity primary key,
    tm_id bigint not null,
    start_ts timestamp(6) with time zone not null,
    end_ts timestamp(6) with time zone not null,
    reason varchar(255),
    team_id bigint,
    constraint fk_leave_member foreign key (tm_id) references team_member (tm_id),
    constraint fk_leave_team foreign key (team_id) references team (team_id)
);

create table break_time (
    break_id bigint generated by default as identity primary key,
    tm_id bigint not null,
    start_ts timestamp(6) with time zone not null,
    end_ts timestamp(6) with time zone not null,
    reason varchar(255),
    team_id bigint,
    constraint fk_break_member foreign key (tm_id) references team_member (tm_id),
    constraint fk_break_team foreign key (team_id) references team (team_id)
);

create table team_membership (
    membership_id bigint generated by default as identity primary key,
    u_id bigint not null,
    team_id bigint not null,
    role varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    constraint uq_team_membership unique (u_id, team_id),
    constraint fk_team_membership_user foreign key (u_id) references users (u_id),
    constraint fk_team_membership_team foreign key (team_id) references team (team_id)
);

create table servicenow_run_log (
    log_id bigint generated by default as identity primary key,
    timestamp timestamp(6) with time zone not null,
    team_id bigint not null,
    team_name varchar(255) not null,
    type varchar(255) not null,
    status varchar(255) not null,
    message varchar(2000),
    incident_count integer not null,
    incidents_json text,
    assignment_selections_json text,
    assignment_results_json text,
    assignment_confirmation varchar(1000),
    constraint fk_servicenow_run_log_team foreign key (team_id) references team (team_id)
);
