import React from 'react';
import { Link } from 'react-router-dom';
import './MarketingHomePage.css';
import './PrivacyPolicyPage.css';

const lastUpdated = 'May 24, 2026';
const contactEmail = 'parthsarvan@psarvans.com';

const policySections = [
  {
    id: 'data-collected',
    title: 'Data InciTeam Collects',
    body: [
      'Account and workspace data: name, username, work email address, organization, team membership, role, invitation status, and authentication-related records.',
      'Setup data: team names, geos, shifts, schedules, rosters, leaves, breaks, configuration items, CI owner mappings, assignment groups, and ServiceNow connection settings entered by administrators.',
      'Operational data: incident identifiers and metadata received from ServiceNow, assignment decisions, assignment results, poller status, diagnostics, logs, and coverage summaries.',
      'Notification data: email recipients, Slack destination labels and webhook configuration when enabled, notification preferences, and mobile push notification device tokens when a user enables push notifications in the iOS app.',
      'Technical data: security, access, and system logs generated by the web app, backend, hosting infrastructure, and connected services so we can operate, debug, and protect the service.',
    ],
  },
  {
    id: 'why',
    title: 'Why This Data Is Used',
    body: [
      'To create and secure organization and team workspaces.',
      'To connect to ServiceNow, read eligible incidents, evaluate CI ownership and availability, and update assignments or work notes when configured.',
      'To show rosters, schedules, coverage gaps, assignment logs, diagnostics, and operational summaries to authorized users.',
      'To send team notifications for selected scenarios such as assignment success, skipped assignment, unsupported CI, or poller and connection failures.',
      'To troubleshoot issues, prevent misuse, maintain reliability, and support customer requests.',
    ],
  },
  {
    id: 'servicenow-aws',
    title: 'ServiceNow, AWS, And Backend Usage',
    body: [
      'InciTeam exchanges data with the ServiceNow instance configured by your organization. This can include reading incident records, validating users and configuration items, assigning incidents, and adding work notes or assignment history.',
      'The InciTeam backend stores application data in managed server infrastructure and database services. AWS services may be used for hosting, storage, logs, and email delivery through Amazon SES when email notifications are enabled.',
      'ServiceNow credentials, Slack webhooks, and email configuration values are used only to provide the requested integration and notification behavior. Access to these values should be limited to authorized administrators.',
    ],
  },
  {
    id: 'push',
    title: 'Push Notification Device Tokens',
    body: [
      'If a user enables iOS push notifications, Apple provides a device token that can be stored with that user account.',
      'InciTeam uses push notification tokens only to send InciTeam operational alerts, such as assignment and coverage notifications. Tokens are not sold or used for advertising.',
      'Tokens may be removed when a user logs out, disables notifications, deletes the account, or when the token is no longer valid.',
    ],
  },
  {
    id: 'ads-tracking',
    title: 'Ads, Tracking, And Sharing',
    body: [
      'InciTeam does not sell personal data.',
      'InciTeam does not use advertising trackers or cross-app tracking.',
      'InciTeam may share data with service providers only as needed to run the product, such as hosting, email delivery, logs, ServiceNow integration, and push notification delivery.',
    ],
  },
  {
    id: 'retention',
    title: 'Retention And Security',
    body: [
      'InciTeam keeps account and setup data for as long as needed to provide the service. Operational ServiceNow run logs are retained for up to 30 days, unless longer retention is needed to comply with legal obligations, resolve disputes, protect the product, or investigate support and security issues.',
      'Administrators should avoid entering unnecessary sensitive data into incident fields, labels, notes, or notification destinations.',
      'InciTeam uses reasonable administrative and technical safeguards, but no internet-connected service can guarantee absolute security.',
    ],
  },
  {
    id: 'deletion',
    title: 'Account Deletion Requests',
    body: [
      'Signed-in users can request account deletion from the Account page in the InciTeam web app.',
      'Organization administrators can delete user accounts from User Access or by deleting a linked team member record.',
      `You can also contact ${contactEmail} from the email address associated with your account if you need help with deletion.`,
      'Deletion removes the login, team access, push notification tokens, and roster records linked to the account, including routing mappings, schedules, leaves, and breaks. Operational logs age out after 30 days unless longer retention is needed for security, legal obligations, or troubleshooting.',
    ],
  },
  {
    id: 'contact',
    title: 'Contact',
    body: [
      `For privacy questions, data requests, or account deletion requests, email ${contactEmail}.`,
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="privacy-page">
      <header className="marketing-nav privacy-nav">
        <Link className="privacy-brand-link" to="/">
          <div className="marketing-nav__brand">
            <div className="marketing-nav__eyebrow">Incident and Team Management Platform</div>
            <div className="marketing-nav__name">InciTeam</div>
          </div>
        </Link>
        <nav className="marketing-nav__links">
          <Link to="/">Home</Link>
          <Link to="/signin">Sign In</Link>
        </nav>
      </header>

      <main className="privacy-main">
        <section className="privacy-hero">
          <div className="marketing-section__eyebrow">Privacy Policy</div>
          <h1>InciTeam Privacy Policy</h1>
          <p>
            This policy explains what information InciTeam collects, why it is used,
            how connected services support the product, and how users can request account
            or data deletion.
          </p>
          <div className="privacy-meta">Last updated: {lastUpdated}</div>
        </section>

        <div className="privacy-layout">
          <aside className="privacy-toc" aria-label="Privacy policy sections">
            {policySections.map((section) => (
              <a key={section.id} href={`#${section.id}`}>
                {section.title}
              </a>
            ))}
          </aside>

          <article className="privacy-content">
            {policySections.map((section) => (
              <section className="privacy-section" id={section.id} key={section.id}>
                <h2>{section.title}</h2>
                <ul>
                  {section.body.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              </section>
            ))}

            <section className="privacy-section privacy-section--note">
              <h2>Changes To This Policy</h2>
              <p>
                InciTeam may update this policy when the product, integrations, legal
                requirements, or account deletion flow changes. The latest version will be
                posted on this page.
              </p>
            </section>
          </article>
        </div>
      </main>

      <footer className="legal-footer legal-footer--marketing">
        <div className="legal-footer__brand">InciTeam™</div>
        <div>
          <Link to="/privacy">Privacy Policy</Link>
        </div>
        <div>Copyright © 2026 Parth Sarvan. All Rights Reserved.</div>
        <div>U.S. Trademark Application Serial No. 99808275 pending.</div>
        <div>U.S. Copyright Case No. 1-15157770821 pending.</div>
      </footer>
    </div>
  );
}
